apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webhook-slack-external-secret
  namespace: monitoring
spec:
  refreshInterval: 1h

  secretStoreRef: # refer to secret store 
    name: aws-secret-store
    kind: ClusterSecretStore

  # 
  target:
    name: alertmanager-slack # name of the secret inside k8s will be created 
    creationPolicy: Owner # to be able to delete secret when external secret deleted
  data:
    - secretKey: slack-webhook # name of value inside k8s secret 
      remoteRef:
        key: slack-secret-ASM # name of secret in aws secret manager
        property: SLACK_WEBHOOK_URL # name of property in aws secret manager