apiVersion: v1
kind: LimitRange
metadata:
  name: monitoring-limits
  namespace: monitoring

spec:
  limits:
  - type: Container

    defaultRequest:
      cpu: 100m
      memory: 256Mi

    default:
      cpu: 500m
      memory: 5121Mi

    min:
      cpu: 25m
      memory: 256Mi

    max:
      cpu: 500m
      memory: 1000Mi