apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring

spec:
  hard:
    # CPU
    requests.cpu: "1"
    limits.cpu: "2"

    # Memory
    requests.memory: 1000Mi
    limits.memory: 2000Mi

    # Storage
    requests.storage: 30Gi

    # Objects
    pods: "25"
    services: "15"
    configmaps: "30"
    secrets: "30"

    # Persistent Volumes
    persistentvolumeclaims: "5"