apiVersion: v1
kind: LimitRange
metadata:
  name: istio-limits
  namespace: istio-system

spec:
  limits:
  - type: Container

    defaultRequest:
      cpu: 100m
      memory: 256Mi

    default:
      cpu: 500m
      memory: 512Mi

    min:
      cpu: 25m
      memory: 256Mi

    max:
      cpu: 500m
      memory: 1000Mi