{{- if .Values.global.back_canary_enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
    name: devops-app-back-dr
    namespace: devops-app
spec:
    host: {{ .Values.global.backend_host }}  # service name that selector both canary , stable pod of front 
    subsets:
    - name: stable
      labels:
        version: stable
        
    - name: canary
      labels:
        version: canary

{{- end }}