[master]
ci-master ansible_host=10.100.1.251

[agents]
ci-agent-1 ansible_host=10.100.2.62
ci-agent-2 ansible_host=10.100.2.56

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/ssh-private-key.pem
ansible_ssh_common_args='-o ProxyJump=bastion'
