kind: ConfigMap
apiVersion: v1
metadata:
  name: front-cm
  labels:
{{ include "back-chart.labels" . | nindent 4 }}
data:
    REACT_APP_API_HOST: {{ .Values.global.backend_host }}
    REACT_APP_API_PORT: "5000"

