apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: devops-app-gateway
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.global.hostname }} #devops-app.mycloudlab.website -> in prod
spec:
  selector:
    istio: gateway    # select pod with label `istio=ingressgateway` -> pod of istio-ingressgateway deployment
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.global.hostname }}