apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: devops-app-vs

spec:
  gateways:
    - devops-app-gateway

  hosts:
    # - devops-app.mycloudlab.website
    - {{ .Values.global.hostname }}

  http:


    - match:
        - uri:
            prefix: /api
      rewrite:
        uriRegexRewrite:
          match: '^/api(/.*)?$'
          rewrite: '\1'



      route:
      {{- if .Values.global.back_canary_enabled }}
        - destination:
            host: {{ .Values.global.backend_host }}
            subset: stable
            port:
              number: 5000
          weight: {{ (index .Values "back-chart" "canary" "weight" "stable") | default 100 }}

        - destination:
            host: {{ .Values.global.backend_host }}
            subset: canary
            port:
              number: 5000
          weight: {{ (index .Values "back-chart" "canary" "weight" "canary") | default 0 }}

        {{- else -}}
        - destination:
            host: {{ .Values.global.backend_host }}
            port:
              number: 5000
        {{- end }}




  
    - match:
        - uri:
            prefix: /


      route:
      {{- if .Values.global.front_canary_enabled }}
        - destination:
            host: {{ .Values.global.frontend_host }} # svc of both front end 
            subset: stable
            port:
              number: 8080
          weight: {{ .Values.canary.weight | default 100 }}

        - destination:
            host: {{ .Values.global.frontend_host }}
            subset: canary
            port:
              number: 8080
          weight: {{ .Values.stable.weight | default 0 }}

      {{- else -}}
      - destination:
            host: {{ .Values.global.frontend_host }}
            port:
              number: 8080
      {{- end }}