apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: devops-app-vs

spec:
  gateways:
    - devops-app-gateway

  hosts:
    - devops-app.mycloudlab.website

  http:
    - match:
        - uri:
            prefix: /api # come from frontend code with origin/api goes to backend-svc:5000/ and rewrite uri from /api to /
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ .Values.global.backend_host }}
            port:
              number: 5000

    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Values.global.frontend_host }}
            port:
              number: 8080